### ISSUE TITLE
Error: CondaEnvException: Pip failed

### ISSUE THREAD

**Issue by Huhaowen0130** [neuroethology/MARS_Developer#48] opened 2021-12-27 08:06 UTC
Hello! When I installed MARS environment with "conda env create -f mars_dev_linux.yml" on Ubuntu 18.04.5 LTS, an error occured as below:
![image](https://user-images.githubusercontent.com/54608650/147449781-c1c1aabf-03ae-4ed5-90f7-da90ea523e96.png)
May I ask how to deal with it? Thank you!

**Comment by annkennedy** [comment] 2022-01-02 03:58
Sorry for the slow reply. This was caused by a mistake in our linux conda environment- the marseval package should not be included in the environment.yml file, but rather it should be installed separately (see installation instructions). This should be fixed now, try pulling from the master branch and let me know if you still have any issues!

**Closed** 2022-01-05 08:57 UTC
